import argparse
import os
from typing import Any, Dict, List

from .utils import load_json


def _check_required_keys(obj: Dict[str, Any], keys: List[str], ctx: str, errors: List[str]) -> None:
    for k in keys:
        if k not in obj:
            errors.append(f"[{ctx}] missing key: {k}")


def validate_a(package_dir: str) -> bool:
    package_dir = os.path.abspath(package_dir)

    metadata_path = os.path.join(package_dir, "metadata.json")
    manifest_path = os.path.join(package_dir, "manifest.json")
    hashes_path = os.path.join(package_dir, "hashes.json")

    errors: List[str] = []

    for p in [metadata_path, manifest_path, hashes_path]:
        if not os.path.exists(p):
            errors.append(f"[validate-a] missing required file: {p}")

    if errors:
        for e in errors:
            print(e)
        return False

    metadata = load_json(metadata_path)
    manifest = load_json(manifest_path)
    hashes_root = load_json(hashes_path)

    # Check top-level FREEZE-A structure (minimal, schema-independent)
    _check_required_keys(metadata, ["proto_version", "package_type", "metadata"], "metadata_root", errors)
    if metadata.get("package_type") != "FREEZE_A":
        errors.append("[metadata_root] package_type must be 'FREEZE_A'")

    meta_inner = metadata.get("metadata", {})
    _check_required_keys(meta_inner, ["id", "five_fingerprint"], "metadata", errors)

    ff = meta_inner.get("five_fingerprint", {})
    _check_required_keys(
        ff,
        ["code_git_hash", "data_version", "spec_hash", "random_seed", "env_fingerprint"],
        "five_fingerprint",
        errors,
    )

    # manifest.files basic checks
    files = manifest.get("files", [])
    if not isinstance(files, list):
        errors.append("[manifest] 'files' must be a list")
    else:
        for idx, item in enumerate(files):
            ctx = f"manifest.files[{idx}]"
            _check_required_keys(item, ["path", "role"], ctx, errors)

    # hashes basic checks
    hashes = hashes_root.get("hashes", {})
    if not isinstance(hashes, dict):
        errors.append("[hashes] must be an object/dict")

    if errors:
        print("[nb-freeze] FREEZE-A validation FAILED:")
        for e in errors:
            print("  -", e)
        return False

    print("[nb-freeze] FREEZE-A structure looks OK.")
    print("[nb-freeze] (Note: for full schema validation you may use an external JSON Schema validator.)")
    return True


def main(argv=None) -> None:
    parser = argparse.ArgumentParser(description="Validate a NebulaBunny FREEZE-A package (structure only).")
    parser.add_argument(
        "package_dir",
        help="Path to the FREEZE-A package directory generated by nb-freeze.",
    )
    args = parser.parse_args(argv)
    ok = validate_a(args.package_dir)
    if not ok:
        raise SystemExit(1)


if __name__ == "__main__":
    main()
